version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for local actions
  - package-ecosystem: "github-actions"
    directory: ".github/actions/setup-actionlint"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: ".github/actions/setup-cabal-docspec"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: ".github/actions/setup-cabal-gild"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: ".github/actions/setup-fourmolu"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: ".github/actions/setup-protoc"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: ".github/actions/setup-shellcheck"
    schedule:
      interval: "daily"
