{
 "title": "Eventlog Live Aggregation",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "HeapSize (Compressed Size)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ghc_eventlog_HeapSize_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HeapSize",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "ghc_eventlog_HeapSize_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MemCurrent (Compressed Size)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ghc_eventlog_MemCurrent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MemCurrent",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "ghc_eventlog_MemCurrent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "BlocksSize (Compressed Size)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ghc_eventlog_BlocksSize_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "BlocksSize",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "ghc_eventlog_BlocksSize_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MemNeeded (Compressed Size)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ghc_eventlog_MemNeeded", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MemNeeded",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "ghc_eventlog_MemNeeded", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HeapLive (Compressed Size)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ghc_eventlog_HeapLive_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HeapLive",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "ghc_eventlog_HeapLive_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MemReturned (Compressed Size)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ghc_eventlog_MemReturned", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MemReturned",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "ghc_eventlog_MemReturned", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HeapAllocated (Compressed Size)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ghc_eventlog_HeapAllocated_bytes_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HeapAllocated",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ghc_eventlog_HeapAllocated_bytes_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HeapProfSample (Compressed Size)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ghc_eventlog_HeapProfSample_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HeapProfSample",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 24 },
   "targets": [
    {
     "expr": "ghc_eventlog_HeapProfSample_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CapabilityUsageDuration (Compressed Size)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ghc_eventlog_CapabilityUsageDuration_nanoseconds_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CapabilityUsageDuration",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ghc_eventlog_CapabilityUsageDuration_nanoseconds_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}