{
 "title": "Eventlog Heap",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "HeapProfSample",
   "type": "timeseries",
   "gridPos": { "h": 24, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "HeapProfSample_bytes", "legendFormat": "{{heapProfLabel}}" }
   ]
  },
  {
   "title": "HeapSize",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "HeapSize_bytes", "legendFormat": "{{__name__}}" },
    { "expr": "BlocksSize_bytes", "legendFormat": "{{__name__}}" },
    { "expr": "HeapLive_bytes", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "MemReturn",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mblock" } },
   "targets": [
    { "expr": "MemCurrent", "legendFormat": "{{__name__}}" },
    { "expr": "MemNeeded", "legendFormat": "{{__name__}}" },
    { "expr": "MemReturned", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "HeapAllocated",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "delta(HeapAllocated_bytes_total[$__interval])",
     "legendFormat": "HeapAllocated_bytes_delta"
    }
   ]
  }
 ]
}