receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:14317"
      http:
        endpoint: "0.0.0.0:14318"

extensions:
  jaeger_query:
    storage:
      traces: some_storage
      metrics: some_metrics_storage
  jaeger_storage:
    backends:
      some_storage:
        memory:
          max_traces: 100000
    metric_backends:
      some_metrics_storage:
        prometheus:
          endpoint: "http://prometheus:9090"
          normalize_calls: true
          normalize_duration: true
  healthcheckv2:
    use_v2: true
    http:

connectors:
  spanmetrics:

processors:
  batch:

exporters:
  jaeger_storage_exporter:
    trace_storage: some_storage
  prometheus:
    endpoint: "0.0.0.0:9090"

service:
  extensions: [jaeger_storage, jaeger_query, healthcheckv2]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter, spanmetrics]
    metrics/spanmetrics:
      receivers: [spanmetrics]
      exporters: [prometheus]
