# syntax=docker/dockerfile:1.7-labs

# To build this image, run:
# docker build --tag well-typed/eventlog-live-otlp:0.1.0.0 --file ./demo/Dockerfile.eventlog-live-otlp .

# Use the Haskell image with GHC 9.10.1
# See: https://hub.docker.com/_/haskell
FROM haskell:9.10-slim-bullseye AS build

# Copy required packages to container
WORKDIR "/eventlog-live"
COPY --parents \
  "./eventlog-live/" \
  "/eventlog-live/"

# Create cabal.project file
COPY <<EOF /eventlog-live/cabal.project
packages: eventlog-live

-- 2025-11-17:
-- disable snappy support in grpc-spec
package grpc-spec
  flags: -snappy

-- 2026-06-24:
-- disable io_uring support in blockio
package blockio
  flags: +serialblockio
EOF

# Install protoc
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y protobuf-compiler

# Build eventlog-live-otlp
RUN <<EOF
cabal update
mkdir "/eventlog-live/bin"
cabal install \
    -f+control \
    --overwrite-policy=always \
    --install-method=copy \
    --installdir="/eventlog-live/bin" \
    eventlog-live-otlp
EOF

# Copy eventlog-live-otlp to output stage
FROM debian:bullseye-slim AS output
COPY --from=build "/eventlog-live/bin/eventlog-live-otlp" "/bin/eventlog-live-otlp"

# Run command
ENTRYPOINT ["/bin/eventlog-live-otlp"]
