{
 "title": "Eventlog Heap",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "HeapProfSample",
   "type": "timeseries",
   "gridPos": { "h": 24, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "HeapProfSample_bytes",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "heapProfLabel::tag" ], "type": "tag" }
     ],
     "legendFormat": "{{heapProfLabel}}",
     "measurement": "HeapProfSample",
     "select": [
      [
       { "params": [ "HeapProfSample" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HeapSize",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "HeapSize_bytes",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "legendFormat": "{{__name__}}",
     "measurement": "HeapSize",
     "select": [
      [
       { "params": [ "HeapSize" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "BlocksSize_bytes",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "legendFormat": "{{__name__}}",
     "measurement": "BlocksSize",
     "select": [
      [
       { "params": [ "BlocksSize" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "HeapLive_bytes",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "legendFormat": "{{__name__}}",
     "measurement": "HeapLive",
     "select": [
      [
       { "params": [ "HeapLive" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "MemReturn",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mblock" } },
   "targets": [
    {
     "expr": "MemCurrent",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{__name__}}",
     "measurement": "MemCurrent",
     "select": [
      [
       { "params": [ "MemCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "MemNeeded",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{__name__}}",
     "measurement": "MemNeeded",
     "select": [
      [
       { "params": [ "MemNeeded" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "MemReturned",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{__name__}}",
     "measurement": "MemReturned",
     "select": [
      [
       { "params": [ "MemReturned" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HeapAllocated",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "delta(HeapAllocated_bytes_total[$__interval])",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "HeapAllocated_bytes_delta",
     "measurement": "HeapAllocated",
     "select": [
      [
       { "params": [ "HeapAllocated" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    }
   ]
  }
 ]
}