{
 "title": "Eventlog Threads",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CapabilityUsage",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "evCap::tag" ], "type": "tag" }
     ],
     "measurement": "CapabilityUsage",
     "select": [
      [
       { "params": [ "CapabilityUsage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Activity by Capacity",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "evCap::tag" ], "type": "tag" }
     ],
     "measurement": "CapabilityUsage",
     "select": [
      [
       { "params": [ "CapabilityUsage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Activity per Thread",
   "type": "state-timeline",
   "gridPos": { "h": 16, "w": 18, "x": 0, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "thread::tag" ], "type": "tag" }
     ],
     "measurement": "ThreadState",
     "query": "SELECT \"threadState\" FROM \"ThreadState\" WHERE $timeFilter GROUP BY \"threadId\"::tag",
     "select": [
      [
       { "params": [ "state" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "ThreadLabel",
   "type": "table",
   "gridPos": { "h": 16, "w": 6, "x": 18, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "thread::tag" ], "type": "tag" }
     ],
     "measurement": "ThreadLabel",
     "select": [
      [
       { "params": [ "label" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}