services:
  fibber:
    image: "wenkokke/fibber:0.1.0.0"
    build:
      context: ".."
      dockerfile: "./dockerfiles/Dockerfile.fibber"
    volumes:
      - "ghc-eventlog-socket:/run/ghc-eventlog-socket"
    environment:
      GHC_EVENTLOG_SOCKET: "/run/ghc-eventlog-socket/ghc-eventlog.sock"
    command: "44"

  eventlog-recv:
    image: "wenkokke/eventlog-recv:0.1.0.0"
    build:
      context: ".."
      dockerfile: "./dockerfiles/Dockerfile.eventlog-recv"
    depends_on:
      fibber:
        condition: "service_started"
    volumes:
      - "ghc-eventlog-socket:/run/ghc-eventlog-socket"
    environment:
      GHC_EVENTLOG_SOCKET: "/run/ghc-eventlog-socket/ghc-eventlog.sock"

volumes:
  ghc-eventlog-socket:
