services:
  oddball:
    # container_name: oddball
    image: "well-typed/eventlog-live-example-oddball:0.1.0.0"
    build:
      context: ".."
      dockerfile: "./dockerfiles/Dockerfile.oddball"
    volumes:
      - "ghc_eventlog_socket:/run/ghc-eventlog-socket"
    environment:
      GHC_EVENTLOG_SOCKET: "/run/ghc-eventlog-socket/ghc-eventlog.sock"
    command:
      - "+RTS"
      - "-l"
      - "-hT"

  collatzer:
    # container_name: collatzer
    image: "well-typed/eventlog-live-example-collatzer:0.1.0.0"
    build:
      context: ".."
      dockerfile: "./dockerfiles/Dockerfile.collatzer"
    depends_on:
      oddball:
        condition: "service_started"
    volumes:
      - "ghc_eventlog_socket:/run/ghc-eventlog-socket"
    environment:
      GHC_EVENTLOG_SOCKET: "/run/ghc-eventlog-socket/ghc-eventlog.sock"

volumes:
  ghc_eventlog_socket:
