# syntax=docker/dockerfile:1.7-labs

# To build this image, run:
# docker build --tag well-typed/eventlog-live-otelcol:0.1.0.0 --file ./dockerfiles/Dockerfile.eventlog-live-otelcol .

# Use the Haskell image with GHC 9.10.1
# See: https://hub.docker.com/_/haskell
FROM haskell:9.10-slim-bullseye AS build

# Copy required packages to container
WORKDIR "/eventlog-live"
COPY --parents \
  "./eventlog-live-otelcol/app/Main.hs" \
  "./eventlog-live-otelcol/CHANGELOG.md" \
  "./eventlog-live-otelcol/eventlog-live-otelcol.cabal" \
  "./eventlog-live-otelcol/LICENSE" \
  "./eventlog-live-otelcol/src/GHC/Eventlog/Live/Otelcol.hs" \
  "./eventlog-live-otelcol/src/System/Random/Compat.hs" \
  "./eventlog-live/CHANGELOG.md" \
  "./eventlog-live/eventlog-live.cabal" \
  "./eventlog-live/LICENSE" \
  "./eventlog-live/src-machines/GHC/Eventlog/Live/Internal/Logger.hs" \
  "./eventlog-live/src-machines/GHC/Eventlog/Live/Machines.hs" \
  "./eventlog-live/src-machines/GHC/Eventlog/Live/Verbosity.hs" \
  "./eventlog-live/src-options/GHC/Eventlog/Live/Options.hs" \
  "./eventlog-live/src-socket/GHC/Eventlog/Live/Socket.hs" \
  "/eventlog-live/"

# Create cabal.project file
COPY <<EOF /eventlog-live/cabal.project
packages: eventlog-live
packages: eventlog-live-otelcol
EOF

# Install protoc
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y protobuf-compiler

# Build eventlog-live-otelcol
RUN <<EOF
cabal update
mkdir "/eventlog-live/bin"
cabal install \
    --overwrite-policy=always \
    --install-method=copy \
    --installdir="/eventlog-live/bin" \
    eventlog-live-otelcol
EOF

# Copy eventlog-live-otelcol to output stage
FROM debian:bullseye-slim AS output
COPY --from=build "/eventlog-live/bin/eventlog-live-otelcol" "/bin/eventlog-live-otelcol"

# Run command
ENTRYPOINT ["/bin/eventlog-live-otelcol"]
