services:
  oddball:
    container_name: oddball
    image: "wenkokke/oddball:0.1.0.0"
    build:
      context: ".."
      dockerfile: "./dockerfiles/Dockerfile.oddball"
    volumes:
      - "ghc_eventlog_socket:/run/ghc-eventlog-socket"
    environment:
      GHC_EVENTLOG_SOCKET: "/run/ghc-eventlog-socket/ghc-eventlog.sock"
    command:
      - "+RTS"
      - "-l"
      - "-hT"
      - "--eventlog-flush-interval=1"

  dumper:
    container_name: dumper
    image: "wenkokke/dumper:0.1.0.0"
    build:
      context: ".."
      dockerfile: "./dockerfiles/Dockerfile.dumper"
    depends_on:
      oddball:
        condition: "service_started"
    volumes:
      - "ghc_eventlog_socket:/run/ghc-eventlog-socket"
    environment:
      GHC_EVENTLOG_SOCKET: "/run/ghc-eventlog-socket/ghc-eventlog.sock"

volumes:
  ghc_eventlog_socket:
