services:
  fibber:
    # container_name: fibber
    image: "well-typed/eventlog-live-example-fibber:0.1.0.0"
    build:
      context: ".."
      dockerfile: "./dockerfiles/Dockerfile.fibber"
    volumes:
      - "ghc_eventlog_socket:/run/ghc-eventlog-socket"
    environment:
      GHC_EVENTLOG_SOCKET: "/run/ghc-eventlog-socket/ghc-eventlog.sock"
    command: "22"

  ghc-events-show:
    # container_name: ghc-events-show
    image: "well-typed/eventlog-live-example-ghc-events-show:0.1.0.0"
    build:
      context: ".."
      dockerfile: "./dockerfiles/Dockerfile.ghc-events-show"
    depends_on:
      fibber:
        condition: "service_started"
    volumes:
      - "ghc_eventlog_socket:/run/ghc-eventlog-socket"
    environment:
      GHC_EVENTLOG_SOCKET: "/run/ghc-eventlog-socket/ghc-eventlog.sock"

volumes:
  ghc_eventlog_socket:
