# syntax=docker/dockerfile:1.7-labs

# To build this image, run:
# docker build --tag wenkokke/ekg-eventlog-influxdb:0.1.0.0 --file ./dockerfiles/Dockerfile.ekg-eventlog-influxdb .

# Use the Haskell image with GHC 9.12.2
# See: https://hub.docker.com/_/haskell
FROM haskell:9.12-slim-bookworm AS build

# Configure ekg-eventlog-influxdb
ARG GHC_EVENTLOG_SOCKET="/tmp/ghc_eventlog.sock"
ENV GHC_EVENTLOG_SOCKET=${GHC_EVENTLOG_SOCKET}
ARG GHC_EVENTLOG_INFLUXDB_HOST="influxdb"
ENV GHC_EVENTLOG_INFLUXDB_HOST=${GHC_EVENTLOG_INFLUXDB_HOST}
ARG GHC_EVENTLOG_INFLUXDB_DB="eventlog"
ENV GHC_EVENTLOG_INFLUXDB_DB=${GHC_EVENTLOG_INFLUXDB_DB}
ARG GHC_EVENTLOG_INFLUXDB_USERNAME="admin"
ENV GHC_EVENTLOG_INFLUXDB_USERNAME=${GHC_EVENTLOG_INFLUXDB_USERNAME}
ARG GHC_EVENTLOG_INFLUXDB_PASSWORD="admin"
ENV GHC_EVENTLOG_INFLUXDB_PASSWORD=${GHC_EVENTLOG_INFLUXDB_PASSWORD}

# Copy required packages to container
WORKDIR "/eventlog-live"
COPY --parents \
    "./ekg-eventlog-core/LICENSE" \
    "./ekg-eventlog-core/ekg-eventlog-core.cabal" \
    "./ekg-eventlog-core/src/System/Metrics/Eventlog.hs" \
    "./ekg-eventlog-influxdb/app/Main.hs" \
    "./ekg-eventlog-influxdb/LICENSE" \
    "./ekg-eventlog-influxdb/ekg-eventlog-influxdb.cabal" \
    "./ekg-eventlog-influxdb/src/System/Metrics/InfluxDB.hs" \
    "/eventlog-live/"

# Create cabal.project file
COPY <<EOF /eventlog-live/cabal.project
packages:
  ekg-eventlog-core
  ekg-eventlog-influxdb

-- NOTE (2025-06-17): Required for GHC version 9.12
if impl(ghc >= 9.12)
  allow-newer:
    , ghc-events:base
    , hashable:base
    , influxdb:base
EOF

# Build ekg-eventlog-influxdb
RUN <<EOF
cabal update
mkdir "/eventlog-live/bin"
cabal install \
    --overwrite-policy=always \
    --install-method=copy \
    --installdir="/eventlog-live/bin" \
    ekg-eventlog-influxdb
EOF

# Copy ekg-eventlog-influxdb to output stage
FROM debian:bookworm-slim AS output
COPY --from=build "/eventlog-live/bin/ekg-eventlog-influxdb" "/bin/ekg-eventlog-influxdb"

# Run command
CMD sleep 5 && ekg-eventlog-influxdb
