# syntax=docker/dockerfile:1.7-labs

# To build this image, run:
# docker build --tag well-typed/eventlog-live-otelcol:0.1.0.0 --file ./dockerfiles/Dockerfile.eventlog-live-otelcol .

# Use the Haskell image with GHC 9.10.1
# See: https://hub.docker.com/_/haskell
FROM haskell:9.10-slim-bullseye AS build

# Copy required packages to container
WORKDIR "/eventlog-live"
COPY --parents \
  "./eventlog-live-otelcol/" \
  "./eventlog-live/" \
  "/eventlog-live/"

# Create cabal.project file
COPY <<EOF /eventlog-live/cabal.project
packages: eventlog-live
packages: eventlog-live-otelcol

-- 2025-11-17:
-- disable snappy support in grpc-spec
package grpc-spec
  flags: -snappy
EOF

# Install protoc
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y protobuf-compiler libsnappy-dev

# Build eventlog-live-otelcol
RUN <<EOF
cabal update
mkdir "/eventlog-live/bin"
cabal install \
    --overwrite-policy=always \
    --install-method=copy \
    --installdir="/eventlog-live/bin" \
    eventlog-live-otelcol
EOF

# Copy eventlog-live-otelcol to output stage
FROM debian:bullseye-slim AS output
COPY --from=build "/eventlog-live/bin/eventlog-live-otelcol" "/bin/eventlog-live-otelcol"

# Run command
ENTRYPOINT ["/bin/eventlog-live-otelcol"]
