name: "Setup Protobuf Compiler"
description: "Install the latest version of the Protobuf Compiler"
inputs:
  protoc-version:
    required: true
    description: "Version of protoc"
runs:
  using: composite
  steps:
    - name: ðŸ’¾ Restore cache
      uses: actions/cache/restore@v4
      if: ${{ !env.ACT }}
      with:
        path: "${{ github.workspace }}/.protoc"
        key: ${{ runner.os }}-protoc-${{ inputs.protoc-version }}
      id: cache-protoc

    - name: ðŸ› ï¸ Install protoc
      if: ${{ env.ACT || steps.cache-protoc.outputs.cache-hit != 'true' }}
      run: |
        mkdir -p "${{ github.workspace }}/.protoc"
        curl -Lo protoc.zip "${{
                    format(
                      'https://github.com/protocolbuffers/protobuf/releases/download/v{0}/protoc-{0}-{1}.zip',
                      inputs.protoc-version,
                      (runner.os == 'Linux' && 'linux-x86_64') || (runner.os == 'macOS' && 'osx-aarch_64') || (runner.os == 'Windows' && 'win64')
                    )
                  }}"
        unzip protoc.zip -d "${{ github.workspace }}/.protoc"
      shell: bash

    - name: ðŸ› ï¸ Add ShellCheck to PATH
      run: echo "${{ github.workspace }}/.protoc/bin" >> "$GITHUB_PATH"
      shell: sh

    - name: ðŸ’¾ Save Cabal dependencies
      uses: actions/cache/save@v4
      if: ${{ !env.ACT && steps.cache-protoc.outputs.cache-hit != 'true' }}
      with:
        path: "${{ github.workspace }}/.protoc/bin"
        key: ${{ steps.cache-protoc.outputs.cache-primary-key }}
