{
 "title": "Eventlog Heap",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(ghc_eventlog_HeapSize_bytes,exported_job)"
    }
   },
   { "name": "heap_prof_sample_limit", "label": "HeapProfSample Limit", "query": "10" },
   { "name": "user_marker_filter", "label": "Filter UserMarker" }
  ]
 },
 "panels": [
  {
   "title": "HeapSize for ${service_name}",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(exported_job) (ghc_eventlog_HeapSize_bytes{exported_job=~\"$service_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage for ${service_name}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "repeat": "service_name"
  },
  {
   "title": "HeapProfSample for ${service_name}",
   "type": "timeseries",
   "gridPos": { "h": 22, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(ghc_eventlog_HeapProfSample_bytes{exported_job=\"${service_name}\"}\nand\ntopk(\n  ${heap_prof_sample_limit},\n  sum_over_time(ghc_eventlog_HeapProfSample_bytes{exported_job=\"${service_name}\"}[${__range}] @ ${__to:date:seconds})\n))\nor\nsum by(exported_job) ((ghc_eventlog_HeapProfSample_bytes{exported_job=\"${service_name}\"}\nunless\ntopk(\n  ${heap_prof_sample_limit},\n  sum_over_time(ghc_eventlog_HeapProfSample_bytes{exported_job=\"${service_name}\"}[${__range}] @ ${__to:date:seconds})\n)))",
     "legendFormat": "{{heapProfLabel}}"
    }
   ]
  },
  {
   "title": "HeapSize for ${service_name}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(ghc_eventlog_HeapSize_bytes{exported_job=\"$service_name\"})",
     "legendFormat": "HeapSize"
    },
    {
     "expr": "avg(ghc_eventlog_BlocksSize_bytes{exported_job=\"$service_name\"})",
     "legendFormat": "BlocksSize"
    },
    {
     "expr": "avg(ghc_eventlog_HeapLive_bytes{exported_job=\"$service_name\"})",
     "legendFormat": "HeapLive"
    }
   ]
  },
  {
   "title": "MemReturn for ${service_name}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "mblock" } },
   "targets": [
    {
     "expr": "avg(ghc_eventlog_MemCurrent{exported_job=\"$service_name\"})",
     "legendFormat": "MemCurrent"
    },
    {
     "expr": "avg(ghc_eventlog_MemNeeded{exported_job=\"$service_name\"})",
     "legendFormat": "MemNeeded"
    },
    {
     "expr": "avg(ghc_eventlog_MemReturned{exported_job=\"$service_name\"})",
     "legendFormat": "MemReturned"
    }
   ]
  },
  {
   "title": "HeapAllocated for ${service_name}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(exported_job) (delta(ghc_eventlog_HeapAllocated_bytes_total{exported_job=\"$service_name\"}[$__interval]))",
     "legendFormat": "HeapAllocated"
    }
   ]
  },
  {
   "type": "cloudspout-button-panel",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 30 },
   "targets": [
    { "direction": "backward" }
   ]
  },
  {
   "type": "cloudspout-button-panel",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 30 },
   "targets": [
    { "direction": "backward" }
   ]
  },
  {
   "type": "cloudspout-button-panel",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 30 },
   "targets": [
    { "direction": "backward" }
   ]
  }
 ]
}