services:
  oddball:
    # container_name: oddball
    image: "well-typed/eventlog-live-example-oddball:0.1.0.0"
    build:
      context: "../.."
      dockerfile: "./dockerfiles/Dockerfile.oddball"
    volumes:
      - "ghc_eventlog_socket:/run/ghc-eventlog-socket"
    environment:
      GHC_EVENTLOG_SOCKET: "/run/ghc-eventlog-socket/ghc-eventlog.sock"
    command:
      - "+RTS"
      - "-l"
      - "-hT"
      - "--eventlog-flush-interval=1"

  eventlog-live-otelcol:
    # container_name: eventlog-live-otelcol
    image: "well-typed/eventlog-live-otelcol:0.1.0.0"
    build:
      context: "../.."
      dockerfile: "./dockerfiles/Dockerfile.eventlog-live-otelcol"
    depends_on:
      oddball:
        condition: "service_started"
      otelcol:
        condition: "service_started"
    volumes:
      - "ghc_eventlog_socket:/run/ghc-eventlog-socket"
    command:
      - "--eventlog-socket=/run/ghc-eventlog-socket/ghc-eventlog.sock"
      - "-hT"
      - "--otelcol-host=otelcol"

  grafana:
    # container_name: grafana
    image: grafana/grafana-oss:latest
    ports:
      - "3000:3000"
    healthcheck:
      test: "curl -f http://localhost:3000/api/health"
      interval: 1m
      timeout: 10s
      retries: 5
    volumes:
      - "./config/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml"
      - "./config/grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml"
      - "./config/grafana-dashboards-eventlog-heap.json:/var/lib/grafana/dashboards/eventlog-heap.json"

  otelcol:
    # container_name: otelcol
    image: otel/opentelemetry-collector-contrib:latest
    command:
      - "--config=/etc/otelcol/config.yaml"
    volumes:
      - "./config/otelcol.yaml:/etc/otelcol/config.yaml"
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
      - "55679:55679" # zPages extension

  prometheus:
    # container_name: prometheus
    image: prom/prometheus:latest
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    volumes:
      - "./config/prometheus.yaml:/etc/prometheus/prometheus.yaml"
    ports:
      - "9090:9090" # Prometheus

  jaeger:
    # container_name: jaeger
    image: jaegertracing/jaeger
    ports:
      - "14317:4317" # OTLP gRPC receiver
      - "14318:4318" # OTLP HTTP receiver
      - "16686:16686" # Jaeger

  tempo:
    # container_name: tempo
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - "./config/tempo.yaml:/etc/tempo.yaml"
    ports:
      - "3200:3200" # Tempo
      - "24317:24317" # OTLP gRPC receiver
      - "24318:24318" # OTLP HTTP receiver

volumes:
  ghc_eventlog_socket:
