#!/bin/sh

# Find the repository root directory
REPO_ROOT_DIR="$(CDPATH='' cd -- "$(dirname -- "$(dirname -- "$0")")" && pwd)"

# Read the expected version:
EXPECT_VERSION="$(awk -F'=' '/^cabal=/{print$2}' ./scripts/dev-dependencies.txt)"

# Find cabal:
#
# 1. Use CABAL if it is set.
# 2. Look for cabal-$EXPECTED_VERSION.
# 3. Look for cabal.
#
if [ "${CABAL}" = "" ]; then
  if ! CABAL="$(which "cabal-${EXPECT_VERSION}")"; then
    if ! CABAL="$(which "cabal")"; then
      echo "Requires cabal ${EXPECT_VERSION}; no version found"
      exit 1
    fi
  fi
fi

# Check cabal version:
ACTUAL_VERSION="$("${CABAL}" --numeric-version | head -n 1)"
if [ "${ACTUAL_VERSION}" != "${EXPECT_VERSION}" ]; then
  # Version mismatch is never an error:
  echo "Requires cabal ${EXPECT_VERSION}; version ${ACTUAL_VERSION} found"
fi

# Set the builddir:
BUILDDIR="${REPO_ROOT_DIR}/dist-newstyle/build-from-sdist"
[ -d "${BUILDDIR}" ] && rm -r "${BUILDDIR}"
mkdir -p "${BUILDDIR}"

# Build the sdists:
${CABAL} sdist all --output-directory="${BUILDDIR}/sdist"

# Extract the sdists:
find "${BUILDDIR}/sdist/" -name '*.tar.gz' -type f -print | while IFS= read -r sdist; do
	tar -xzvf "${sdist}" -C "${BUILDDIR}"
done

# Write a cabal.project file:
CABAL_PROJECT="${BUILDDIR}/cabal.project"
{
	echo "-- This file was generated by scripts/build-from-sdist.sh";
	cat "${REPO_ROOT_DIR}/cabal.project.config";
	echo
} >> "${CABAL_PROJECT}"
find "${BUILDDIR}" -type d -mindepth 1 -maxdepth 1 -not -name 'sdist' | while IFS= read -r pkg; do
	echo "packages: ${pkg}" >> "${CABAL_PROJECT}"
done


# Build all packages:
${CABAL} build all --builddir="${BUILDDIR}" --project-dir="${BUILDDIR}" "$@"
