services:
  otelcol:
    # container_name: otelcol
    image: otel/opentelemetry-collector-contrib:latest
    command:
      - "--config=/etc/otelcol/config.yaml"
      - "--set=exporters.otlp.headers.x-honeycomb-team=${X_HONEYCOMB_TEAM}"
      - "--set=exporters.otlp/metrics.headers.x-honeycomb-team=${X_HONEYCOMB_TEAM}"
      - "--set=exporters.otlp/metrics.headers.x-honeycomb-dataset=${X_HONEYCOMB_DATASET}"
    volumes:
      - "./config/otelcol.yaml:/etc/otelcol/config.yaml"
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
      - "55679:55679" # zPages extension

