services:
  oddball:
    # container_name: oddball
    image: "well-typed/eventlog-live-example-oddball:0.1.0.0"
    build:
      context: "../.."
      dockerfile: "./dockerfiles/Dockerfile.oddball"
    volumes:
      - "ghc_eventlog_socket:/run/ghc-eventlog-socket"
    environment:
      GHC_EVENTLOG_SOCKET: "/run/ghc-eventlog-socket/ghc-eventlog.sock"
    command:
      - "+RTS"
      - "-l"
      - "-hT"
      - "--eventlog-flush-interval=1"

  eventlog-live-otelcol:
    # container_name: eventlog-live-otelcol
    image: "well-typed/eventlog-live-otelcol:0.1.0.0"
    build:
      context: "../.."
      dockerfile: "./dockerfiles/Dockerfile.eventlog-live-otelcol"
    depends_on:
      oddball:
        condition: "service_started"
      otelcol:
        condition: "service_started"
    volumes:
      - "ghc_eventlog_socket:/run/ghc-eventlog-socket"
    command:
      - "--eventlog-socket=/run/ghc-eventlog-socket/ghc-eventlog.sock"
      - "-hT"
      - "--otelcol-host=otelcol"

  otelcol:
    # container_name: otelcol
    image: otel/opentelemetry-collector-contrib:latest
    command:
      - "--config=/etc/otelcol/config.yaml"
    volumes:
      - "./config/otelcol.yaml:/etc/otelcol/config.yaml"
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
      - "55679:55679" # zPages extension

volumes:
  ghc_eventlog_socket:
