{
 "title": "Heap Stats",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "heap_items",
    "label": "Heap Items",
    "query": "SHOW MEASUREMENTS ON eventlog WITH MEASUREMENT =~ /heap_prof_sample/"
   }
  ]
 },
 "panels": [
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "Heap Size",
     "groupBy": [
      { "params": [ "$$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gauge.eventlog.heap_size",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Live Bytes",
     "groupBy": [
      { "params": [ "$$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gauge.eventlog.live_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Blocks Size",
     "groupBy": [
      { "params": [ "$$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gauge.eventlog.blocks_size",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latest Heap Census",
   "type": "table",
   "gridPos": { "h": 17, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "limit": "1",
     "measurement": "/^$$heap_items$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "measurement_name" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heap Samples",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 11 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$$heap_items$/",
     "query": "SELECT mean(\"value\") FROM /heap_prof_sample/ WHERE $$timeFilter GROUP BY time($$__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}