services:
  oddball:
    # container_name: oddball
    image: "well-typed/eventlog-live-example-oddball:0.1.0.0"
    build:
      context: "../.."
      dockerfile: "./dockerfiles/Dockerfile.oddball"
    volumes:
      - "ghc_eventlog_socket:/run/ghc-eventlog-socket"
    environment:
      GHC_EVENTLOG_SOCKET: "/run/ghc-eventlog-socket/ghc-eventlog.sock"
    command:
      - "+RTS"
      - "-l"
      - "-hT"
      - "--eventlog-flush-interval=1"

  eventlog-live-influxdb:
    # container_name: eventlog-live-influxdb
    image: "well-typed/eventlog-live-influxdb:0.1.0.0"
    restart: "unless-stopped"
    build:
      context: "../.."
      dockerfile: "./dockerfiles/Dockerfile.eventlog-live-influxdb"
    depends_on:
      oddball:
        condition: "service_started"
      influxdb:
        condition: "service_started"
    volumes:
      - "ghc_eventlog_socket:/run/ghc-eventlog-socket"
    command:
      - "--eventlog-socket=/run/ghc-eventlog-socket/ghc-eventlog.sock"
      - "-hT"
      - "--influxdb-host=influxdb"
      - "--influxdb-database=eventlog"
      - "--influxdb-username=admin"
      - "--influxdb-password=admin"

  grafana:
    # container_name: grafana
    image: "grafana/grafana"
    restart: "unless-stopped"
    ports:
      - "3000:3000"
    healthcheck:
      test: "curl -f http://localhost:3000/api/health"
      interval: 1m
      timeout: 10s
      retries: 5
    volumes:
      - "./config/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml"
      - "./config/grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml"
      - "./config/grafana-dashboards-eventlog-heap.json:/var/lib/grafana/dashboards/eventlog-heap.json"
      - "./config/grafana-dashboards-eventlog-threads.json:/var/lib/grafana/dashboards/eventlog-threads.json"

  influxdb:
    # container_name: influxdb
    image: "influxdb:1.8"
    restart: "always"
    ports:
      - "8086:8086"
    healthcheck:
      test: "curl -f http://localhost:8086/ping"
      interval: 1m
      timeout: 10s
      retries: 5
    environment:
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_DB: "eventlog"
      INFLUXDB_ADMIN_USER: "admin"
      INFLUXDB_ADMIN_PASSWORD: "admin"

volumes:
  ghc_eventlog_socket:
